name: Test Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: "Lint"
    runs-on: [self-hosted, production-medium]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
      - run: make install
      - run: make lint

  tests:
    needs: [lint]
    name: "Unit Tests"
    runs-on: [self-hosted, production-medium]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
      - run: make install
      - run: make test
