name: Test Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - run: make install
      - run: make lint

  tests:
    needs: [lint]
    name: "Unit Tests"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - run: make install
      - run: make test
